salary=float(input("Please enter your salary: "))
month=input("Please enter the name of the month: ")
print("Please enter the percentages for each:")
savingsper=float(input("Savings(%): "))
rentper=float(input("Rent(%): "))
electricityper=float(input("Electricity(%): "))
savings=salary*(savingsper/100)
rent=salary*(rentper/100)